version: "3.9"
services:
  ollama-intel-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-intel-gpu
    image: ollama-intel-gpu:latest
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ollama-intel-gpu:/root/.ollama
    environment:
      - DISPLAY=${DISPLAY}
      - ONEAPI_DEVICE_SELECTOR=gpu
      - ZE_AFFINITY_MASK=0.0
      - IPEX_XPU_BACKEND=gpu
      - OCL_ICD_FILENAMES=/opt/intel/opencl/libintelocl.so
      - SYCL_DEVICE_FILTER=opencl:gpu
      - ZES_ENABLE_SYSMAN=1
      - OLLAMA_INTEL_GPU=true
      - DEVICE=Arc
    shm_size: '16gb'
  ollama-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama-intel-gpu
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama-intel-gpu:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  ollama-webui: {}
  ollama-intel-gpu: {}
